name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    branches: [ master ]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ windows-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: ./gradlew clean
      - run: ./gradlew check

  ubuntu-test-and-analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: gradle/wrapper-validation-action@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Clean
      run: ./gradlew clean
    - name: Run Tests and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew check sonarqube
